name: mvvm_bloc_example
version: 0.0.2
author: Tanapoj Chaivanichanan <tanapoj@centrilliontech.co.th>
homepage: https://github.com/nartra/flutter_mvvm_arch

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mvvm_bloc: ^1.0.1
  event_bus: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: