name: mvvm_bloc
description: Flutter MVVM Architecture with BLoC Pattern
version: 0.0.2
author:
homepage: https://github.com/tanapoj/flutter_mvvm_bloc

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_live_data: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: