name: mvvm_bloc
description: Flutter MVVM Architecture with BLoC Pattern
version: 1.0.4
author:
homepage: https://github.com/tanapoj/flutter_mvvm_bloc

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_live_data: ^1.0.1
  bloc_builder: ^1.0.1

  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: